# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://ikydcpgpuvgdynwaedyw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreWRjcGdwdXZnZHlud2FlZHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTgwMzk1MTIsImV4cCI6MjAzMzYxNTUxMn0.zxaiwjcjsi2rPgIq8uEVKhi_5AxVJeu1S2W-Z2yhBWA"